cl_time_ntp_servers:
  - 0.cumulusnetworks.pool.ntp.org iburst
  - 1.cumulusnetworks.pool.ntp.org 
  - 2.cumulusnetworks.pool.ntp.org 
  - 3.cumulusnetworks.pool.ntp.org 

cl_time_ntp_source: eth1

cl_locales:
  - en_US.UTF-8 UTF-8

cl_dns_nameserver:
  ipv4:
    - 9.9.9.9
    - 1.1.1.1
  ipv6:
    - 2620:fe::fe

cl_snmp:
  listening-address:
    - 192.168.1.10
    - 192.168.1.20
  readonly-community:
    my_rocommunity:
      access: any

cl_syslog:
  ipv4:
    - ip: 192.168.1.10
      port: 5000
      proto: tcp

cl_commands:
  add:
    vrf: mgmt
  del:
    snmp-server: all
