---
# Settings that apply to all dw2 firewalls, production and test

opn_vlan_interfaces_common:
  - interface: opt1
    vlan: 114
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-mgm-114
  - interface: opt2
    vlan: 115
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-srv-115
  - interface: opt3
    vlan: 116
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-sec-116
  - interface: opt4
    vlan: 117
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-fac-117

opn_vlans:
  - tag: 114
    settings:
      - key: descr
        value: "dw2-mgm-114"
  - tag: 115
    settings:
      - key: descr
        value: "dw2-srv-115"
  - tag: 116
    settings:
      - key: descr
        value: "dw2-sec-116"
  - tag: 117
    settings:
      - key: descr
        value: "dw2-fac-117"

opn_filter:
  - descr: Allow pfsync
    settings:
      - key: interface
        value: pfsync
      - key: log
        value: 1
      - key: type
        value: pass
      - key: ipprotocol
        value: inet
      - key: statetype
        value: keep state
      - key: source/any
        value: 1
      - key: destination/any
        value: 1

opn_gateways:
  - interface: wan
    settings:
      - key: gateway
        value: 192.168.1.1
      - key: name
        value: wan_gateway
      - key: defaultgw
        value: 1
