---
opn_vlan_interfaces_specific:
  - interface: opt1
    settings:
      - key: ipaddr
        value: 10.114.0.3
  - interface: opt2
    settings:
      - key: ipaddr
        value: 10.115.0.3
  - interface: opt3
    settings:
      - key: ipaddr
        value: 10.116.0.3
  - interface: opt4
    settings:
      - key: ipaddr
        value: 10.117.0.3
...
