---
opn_virtualip_a:
  - vhid: 255
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 24
      - key: mode
        value: carp
      - key: interface
        value: wan
      - key: subnet
        value: 145.136.246.219
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
...
