---
opn_vlan_parent_interface: em1

opn_interfaces_common:
  - interface: wan
    settings:
      - key: if
        value: em0
      - key: descr
        value: wan
  - interface: lan
    settings:
      - key: if
        value: em1
      - key: descr
        value: lan
  - interface: pfsync
    settings:
      - key: if
        value: em2
      - key: enable
        value: 1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync

  - interface: opt1
    vlan: 114
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-mgm-114
  - interface: opt2
    vlan: 115
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-srv-115
  - interface: opt3
    vlan: 116
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-sec-116
  - interface: opt4
    vlan: 117
    settings:
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-fac-117

opn_vlans:
  - tag: 114
    settings:
      - key: descr
        value: "dw2-mgm-114"
  - tag: 115
    settings:
      - key: descr
        value: "dw2-srv-115"
  - tag: 116
    settings:
      - key: descr
        value: "dw2-sec-116"
  - tag: 117
    settings:
      - key: descr
        value: "dw2-fac-117"

opn_gateways:
  - interface: wan
    settings:
      - key: gateway
        value: 192.168.1.1
      - key: name
        value: wan_gateway
      - key: defaultgw
        value: 1
