---
ansible_become_method: sudo
ansible_python_interpreter: '/usr/bin/env python2.7'

dnsserver:
  - "8.8.8.8"
  - "8.8.4.4"

opn_user:
  - name: rudi.broekhuizen
    settings:
      - key: descr
        value: "Rudi Broekhuizen"
      - key: scope
        value: user
      - key: groupname
        value: admins
      - key: password
        value: secret
      - key: uid
        value: 1

  - name: foppe.pieters
    settings:
      - key: descr
        value: "Foppe Pieters"
      - key: scope
        value: user
      - key: groupname
        value: admins
      - key: password
        value: secret
      - key: uid
        value: 2

  - name: nick.stolk
    settings:
      - key: descr
        value: "Nick Stolk"
      - key: scope
        value: user
      - key: groupname
        value: admins
      - key: password
        value: secret
      - key: uid
        value: 3

opn_group:
  - name: admins
    settings:
      - member: 1
      - member: 2

  - name: support
    settings:
      - key: descr
        value: Support
      - key: gid
        value: 2000
      - key: priv
        value: page-all
      - member: 3
