---
opn_interfaces_common:
  - if: wan
    settings:
      - key: if
        value: em0
      - key: descr
        value: wan
  - if: lan
    settings:
      - key: if
        value: em1
      - key: descr
        value: lan
  - if: pfsync
    settings:
      - key: if
        value: em2
      - key: enable
        value: 1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync
  - if: opt1
    settings:
      - key: if
        value: em1_vlan114
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-mgm-114
  - if: opt2
    settings:
      - key: if
        value: em1_vlan115
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-srv-115
  - if: opt3
    settings:
      - key: if
        value: em1_vlan116
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-sec-116
  - if: opt4
    settings:
      - key: if
        value: em1_vlan117
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-fac-117
  - if: opt5
    settings:
      - key: if
        value: em1_vlan118
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-srv-118
  - if: opt6
    settings:
      - key: if
        value: em1_vlan119
      - key: enable
        value: 1
      - key: subnet
        value: 16
      - key: descr
        value: dw2-off-119

opn_vlans:
  - tag: 114
    settings:
      - key: if
        value: em1
      - key: descr
        value: "dw2-mgm-114"
      - key: vlanif
        value: em1_vlan114
  - tag: 115
    settings:
      - key: if
        value: em1
      - key: descr
        value: "dw2-srv-115"
      - key: vlanif
        value: em1_vlan115
  - tag: 116
    settings:
      - key: if
        value: em1
      - key: descr
        value: "dw2-sec-116"
      - key: vlanif
        value: em1_vlan116
  - tag: 117
    settings:
      - key: if
        value: em1
      - key: descr
        value: "dw2-fac-117"
      - key: vlanif
        value: em1_vlan117
  - tag: 118
    settings:
      - key: if
        value: em1
      - key: descr
        value: "dw2-srv-118"
      - key: vlanif
        value: em1_vlan118
  - tag: 119
    settings:
      - key: if
        value: em1
      - key: descr
        value: "dw2-off-119"
      - key: vlanif
        value: em1_vlan119
