opn_filter:
  - descr: Allow pfsync
    settings:
      - key: interface
        value: pfsync
      - key: log
        value: 1
      - key: type
        value: pass
      - key: ipprotocol
        value: inet
      - key: source/any
        value: 1
      - key: destination/any
        value: 1

opn_vlan_interfaces_specific:
  - interface: opt1
    settings:
      - key: ipaddr
        value: 10.114.0.3
  - interface: opt2
    settings:
      - key: ipaddr
        value: 10.115.0.3
  - interface: opt3
    settings:
      - key: ipaddr
        value: 10.116.0.3
  - interface: opt4
    settings:
      - key: ipaddr
        value: 10.117.0.3
...
