---
postgresql_listen_addresses:
  - "localhost"
  - "192.168.56.6"

postgresql_pg_hba_custom:
  - type: host
    database: replication
    user: replicator
    address: 192.168.56.0/24
    method: trust
  - type: host
    database: all
    user: postgres
    address: 192.168.56.0/24
    method: trust

postgresql_users:
  - name: postgres
    pass: "{{ 'postgres' | password_hash('sha512') }}"
    encrypted: yes
  - name: replicator
    pass: "{{ 'replicator' | password_hash('sha512') }}"
    encrypted: yes

postgresql_user_privileges:
  - name: replicator
    role_attr_flags: 'REPLICATION,LOGIN'
  - name: postgres
    role_attr_flags: 'SUPERUSER,LOGIN'

postgresql_conf:
  - max_connections: 250
  - archive_mode: "off"
  - work_mem: "'8MB'"
  - wal_level: replica
  - max_wal_senders: 10
  - wal_sender_delay: 1s
  - wal_keep_segments: 0
  - replication_timeout: 60s
  - wal_sender_timeout: 60s
  - max_replication_slots: 2
  - track_commit_timestamp: off

#- synchronous_standby_num_sync:
#- synchronous_standby_choose_sync: "FIRST"
#- synchronous_standby_names: []
#- vacuum_defer_cleanup_age: 0
...