---
postgresql_flavor: pgdg
postgresql_version: 11.1
postgresql_listen_addresses:
  - "localhost"
  - "192.168.56.6"

postgresql_pg_hba_custom:
  - type: host
    database: replication
    user: replicator
    address: 192.168.56.0/24
    method: trust
  - type: host
    database: all
    user: postgres
    address: 192.168.56.0/24
    method: trust

postgresql_users:
  - name: postgres
    pass: "{{ 'postgres' | password_hash('sha512') }}"
    encrypted: yes
  - name: replicator
    pass: "{{ 'replicator' | password_hash('sha512') }}"
    encrypted: yes

postgresql_user_privileges:
  - name: replicator
    role_attr_flags: 'REPLICATION,LOGIN'
  - name: postgres
    #    priv: "ALL"
    #    db: exampledb
    role_attr_flags: 'SUPERUSER,LOGIN'


postgresql_wal_level: replica
postgresql_max_wal_senders: 10
postgresql_wal_sender_delay: 1s         # walsender cycle time, 1-10000 milliseconds (<= 9.1)
postgresql_wal_keep_segments:  0        # in logfile segments, 16MB each; 0 disables
postgresql_replication_timeout: 60s     # in milliseconds; 0 disables (<= 9.2)
postgresql_wal_sender_timeout: 60s      # in milliseconds; 0 disables (>= 9.3)
postgresql_max_replication_slots: 2     # max number of replication slots
postgresql_track_commit_timestamp: off  # (>= 9.5)


# - Master Server -

# These settings are ignored on a standby server.

# standby servers that provide sync rep.
# number of sync standbys (>= 9.6) and comma-separated list of application_name from standby(s)
postgresql_synchronous_standby_num_sync: "" # >= 9.6 (NOTE: If you use the ANY/ALL syntax in v10, then note the new variable below)
postgresql_synchronous_standby_choose_sync: "FIRST" # >= 10
postgresql_synchronous_standby_names: [] # '*' means 'all'

# number of xacts by which cleanup is delayed
postgresql_vacuum_defer_cleanup_age: 0

