---
postgresql_global_config_options:
  - option: listen_addresses
    value: '*'
  - option: wal_level
    value: hot_standby
  - option: archive_mode
    value: on
  - option: archive_command
    value: 'cp -i %p /var/lib/postgresql/11/main/archive/%f'
  - option: max_wal_senders
    value: 3
  - option: wal_keep_segments
    value: 8
  - option: hot_standby
    value: 'on'
...
