---
postgresql_conf:
  - listen_addresses: "'*'"
  - max_connections: 250
  - archive_mode: off
  - work_mem: 8MB
  - wal_level: replica
  - max_wal_senders: 10
  - wal_keep_segments: 0
  - wal_sender_timeout: 60s
  - max_replication_slots: 2
  - track_commit_timestamp: off

postgresql_pg_hba_conf:
  - host replication replicator 192.168.56.0/24 trust

#- synchronous_standby_num_sync:
#- synchronous_standby_choose_sync: "FIRST"
#- synchronous_standby_names: []
#- vacuum_defer_cleanup_age: 0
...
