---
- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    mode: 0644
  when: ansible_lsb.codename == "jessie"

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb-src ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    mode: 0644
  when: ansible_lsb.codename == "jessie"

- name: Install jq and update apt's cache
  apt:
    name: jq
    state: latest
    update_cache: yes

- name: Collect interface metrics
  cron:
    name: "check dirs"
    minute: "0"
    hour: "0"
    job: "net show int json | jq -c '. | to_entries[] | {"interface": .key, "value": .value} | . + .value | del(.value) | . + .iface_obj | del(.iface_obj) | . + .counters | del(.counters)' >> /var/log/nclu-int.json"
