---
- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    mode: 0644
#  when: ansible_lsb.codename == "jessie"

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb-src ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
    mode: 0644
#  when: ansible_lsb.codename == "jessie"

- name: Install jq and update apt's cache
  apt:
    name: jq
    state: latest
    update_cache: yes

- name: Collect interface metrics, run every minute
  cron:
    name: "check dirs"
    job: "net show int json | jq -c '. | to_entries[] | {'interface': .key, 'value': .value} | . + .value | del(.value) | . + .iface_obj | del(.iface_obj) | . + .counters | del(.counters) | if .lldp != null then . + .lldp[] | del(.lldp) | del(.system_descr) else . end'
 >> /var/log/nclu-int.json"

- name: Create rsyslog config file to forward nclu-int.json using rsyslog
  copy:
    src: 60-nclu-int.conf
    dest: /etc/rsyslog.d/60-nclu-int.conf
  notify: Restart rsyslog
