---

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
#    filename: 'jessie'
    mode: 0644
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

- name: Set jessie source list in apt
  apt_repository: 
    repo: "deb-src ftp://ftp.gr.debian.org/debian/ jessie main"
    state: present
#    filename: 'jessie'
    mode: 0644
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'wheezy'

- name: Install jq and update apt's cache
  apt:
    name: jq
    state: latest
    update_cache: yes
