---
- name: Install PostgreSQL
  hosts: postgresql
  become: true
  gather_facts: true
  roles:
    - postgresql

- name: Add replication user to postgresql
  hosts: postgresql-master
  tasks:
    - name: Install packages needed for managing Postgresql with Ansible
      become: true
      apt:
        name: python3-psycopg2
        update_cache: yes
        state: present
    - name: create replication user
      become: true
      become_user: postgres
      postgresql_user:
        user: replicator
        password: password
        role_attr_flags: REPLICATION
...
