# playbook postgresql
---
- name: Install PostgreSQL
  hosts: postgresql
  become: yes
  gather_facts: false
  roles:
    - postgresql

  tasks:
    - name: Create slave
      ios_ping:
        dest: '{{ item }}'
        state: 'present'
      when: "'slave' in inventory_hostname"
      with_items:
        - '10.0.255.1'
