---
- name: Install PostgreSQL
  hosts: postgresql
  become: true
  gather_facts: true
  roles:
    - postgresql

- name: Add replication user to postgresql
  hosts: postgresql-master
  become: true
  tasks:
    - name: Install packages needed for managing Postgresql with Ansible
      apt:
        name: python3-psycopg2 #python-psycopg2
        update_cache: yes
        state: present
    - name: Create replication user
      become_user: postgres
      postgresql_user:
        user: replicator
        password: password
        role_attr_flags: REPLICATION
      tags: postgresql_user
...
