---
# This is used to manage Ansible role and collection dependencies
# See: https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-and-collections-from-the-same-requirements-yml-file
# Install roles with: `ansible-galaxy role install -r requirements.yml -p ./roles/`
# Install collections with: `ansible-galaxy collection install -r requirements.yml -p ./collections/`
roles:
  - name: base
    src: https://gitlab.com/naturalis/lib/ansible-base-role
    scm: git
    version: master
  - name: users
    src: https://gitlab.com/naturalis/lib/ansible-users-sshkeys-role
    scm: git
    version: distro
  - name: docker-compose
    src: https://gitlab.com/naturalis/lib/ansible-docker-compose
    scm: git
    version: multiple
  - name: postgresql
    src: https://gitlab.com/naturalis/lib/ansible-postgresql
    scm: git
    version: master 
  - name: cumuluslinux
    src: https://github.com/maxlareo/ansible-cumuluslinux
  - name: ansible-cumulus-metrics
    src: https://github.com/naturalis/ansible-cumulus-metrics
  - name: mysql
    src: geerlingguy.mysql
  - name: logrotate
    src: nickhammond.logrotate
  - name: restic
    src: https://github.com/paulfantom/ansible-restic
    version: 1f93948
...
