---
# This is used to manage Ansible role dependences
# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# Install with: 'ansible-galaxy install -f -r requirements.yml --roles-path .'

- name: base
  src: https://gitlab.com/naturalis/lib/ansible-base-role.git
  scm: git

- name: postgresql
  src: https://gitlab.com/naturalis/lib/ansible-postgresql
  scm: git
  version: master 

- name: cumuluslinux
  src: https://github.com/maxlareo/ansible-cumuluslinux

- name: ansible-cumulus-metrics
  src: https://github.com/naturalis/ansible-cumulus-metrics

- name: mysql
  src: geerlingguy.mysql

- name: docker
  src: geerlingguy.docker

- name: logrotate
  src: nickhammond.logrotate

- src: https://github.com/paulfantom/ansible-restic
  version: 1f93948
  name: restic
...
