---
ansible_host: 192.168.50.2
ansible_user: root
ansible_ssh_pass: opnsense

opn_singles:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: dw2-fwl-2
      - key: domain
        value: naturalis.nl

opn_interfaces:
  - if: opt1
    settings:
      - key: if
        value: em1_vlan114
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.114.0.3
      - key: subnet
        value: 16
  - if: opt2
    settings:
      - key: if
        value: em1_vlan115
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.115.0.3
      - key: subnet
        value: 16
  - if: opt3
    settings:
      - key: if
        value: em1_vlan116
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.116.0.3
      - key: subnet
        value: 16
  - if: opt4
    settings:
      - key: if
        value: em1_vlan117
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.117.0.3
      - key: subnet
        value: 16
  - if: opt5
    settings:
      - key: if
        value: em1_vlan118
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.118.0.3
      - key: subnet
        value: 16
  - if: opt6
    settings:
      - key: if
        value: em1_vlan119
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.119.0.3
      - key: subnet
        value: 16
