---
ansible_host: 192.168.50.1
ansible_user: root
ansible_ssh_pass: opnsense

primary: true

opn_singles:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: opnsense01
      - key: domain
        value: naturalis.nl

opn_interfaces_specific:
  - if: opt1
    settings:
      - key: ipaddr
        value: 10.114.0.2

opn_interfaces:
  - if: wan
    settings:
      - key: if
        value: em0
      - key: descr
        value: wan
  - if: lan
    settings:
      - key: if
        value: em1
      - key: descr
        value: lan
  - if: pfsync
    settings:
      - key: if
        value: em2
      - key: enable
        value: 1
      - key: ipaddr
        value: 192.168.254.1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync
  - if: opt1
    settings:
      - key: if
        value: em1_vlan114
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.114.0.2
      - key: subnet
        value: 16
      - key: descr
        value: dw2-mgm-114
  - if: opt2
    settings:
      - key: if
        value: em1_vlan115
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.115.0.2
      - key: subnet
        value: 16
      - key: descr
        value: dw2-srv-115
  - if: opt3
    settings:
      - key: if
        value: em1_vlan116
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.116.0.2
      - key: subnet
        value: 16
      - key: descr
        value: dw2-sec-116
  - if: opt4
    settings:
      - key: if
        value: em1_vlan117
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.117.0.2
      - key: subnet
        value: 16
      - key: descr
        value: dw2-fac-117
  - if: opt5
    settings:
      - key: if
        value: em1_vlan118
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.118.0.2
      - key: subnet
        value: 16
      - key: descr
        value: dw2-srv-118
  - if: opt6
    settings:
      - key: if
        value: em1_vlan119
      - key: enable
        value: 1
      - key: ipaddr
        value: 10.119.0.2
      - key: subnet
        value: 16
      - key: descr
        value: dw2-off-119

opn_virtualip:
  - vhid: 114
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt1
      - key: subnet
        value: 10.114.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 115
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt2
      - key: subnet
        value: 10.115.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 116
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt3
      - key: subnet
        value: 10.116.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 117
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt4
      - key: subnet
        value: 10.117.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 118
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt5
      - key: subnet
        value: 10.118.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 119
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt6
      - key: subnet
        value: 10.119.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense        

opn_hasync:
  - xpath: /opnsense/hasync
    settings:
      - key: pfsyncenabled
        value: "on"
      - key: username
        value: root
      - key: password
        value: opnsense
      - key: pfsyncinterface
        value: pfsync
      - key: synchronizetoip
        value: 192.168.254.2
      - key: synchronizeusers
        value: "on"
      - key: synchronizevirtualip
        value: "on"
