---
ansible_host: 192.168.50.1
ansible_user: root
ansible_ssh_pass: opnsense

opn_misc:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: dw2-fwl-1
      - key: domain
        value: naturalis.nl
  - xpath: /opnsense/hasync
    settings:
      - key: pfsyncenabled
        value: "on"
      - key: username
        value: root
      - key: password
        value: opnsense
      - key: pfsyncinterface
        value: pfsync
      - key: pfsyncpeerip
        value: 192.168.254.2
      - key: synchronizetoip
        value: 192.168.254.2
      - key: synchronizeusers
        value: "on"
      - key: synchronizevirtualip
        value: "on"
      - key: synchronizealiases
        value: "on"
      - key: synchronizerules
        value: "on"

opn_interfaces_specific:
#  - if: wan
#    settings:
#      - key: ipaddr
#        value: x.x.x.x
#  - if: lan
#    settings:
#      - key: ipaddr
#        value: x.x.x.x
  - if: pfsync
    settings:
      - key: ipaddr
        value: 192.168.254.1
  - if: opt1
    settings:
      - key: ipaddr
        value: 10.114.0.2
  - if: opt2
    settings:
      - key: ipaddr
        value: 10.115.0.2
  - if: opt3
    settings:
      - key: ipaddr
        value: 10.116.0.2
  - if: opt4
    settings:
      - key: ipaddr
        value: 10.117.0.2
  - if: opt5
    settings:
      - key: ipaddr
        value: 10.118.0.2
  - if: opt6
    settings:
      - key: ipaddr
        value: 10.119.0.2

opn_virtualip:
  - vhid: 114
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt1
      - key: subnet
        value: 10.114.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 115
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt2
      - key: subnet
        value: 10.115.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 116
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt3
      - key: subnet
        value: 10.116.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 117
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt4
      - key: subnet
        value: 10.117.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 118
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt5
      - key: subnet
        value: 10.118.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 119
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt6
      - key: subnet
        value: 10.119.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense

opn_alias:
  - name: ictsupport
    settings:
      - key: type
        value: network
      - key: address
        value: "192.168.103.0/24 172.16.51.61/32 172.16.51.61/32"
      - key: state
        value: present

opn_gateways:
  - interface: wan
    settings:
      - key: gateway
        value: 1.1.1.1
      - key: name
        value: wan_gateway
      - key: defaultgw
        value: 1     
...
