---
ansible_host: 192.168.1.1
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall-primary
      - key: domain
        value: naturalis.nl
  - xpath: /opnsense/nat
    settings:
      - key: outbound/mode
        value: disabled

opn_physical_interfaces:
  - interface: wan
    settings:
      - key: if
        value: em0
      - key: ipaddr
        value: 192.168.100.2
      - key: subnet
        value: 24
      - key: gateway
        value: wan_gateway
      - key: descr
        value: wan
  - interface: lan
    settings:
      - key: if
        value: em1
      - key: ipaddr
        value: 192.168.1.1
      - key: subnet
        value: 24
      - key: descr
        value: lan
  - interface: pfsync
    settings:
      - key: if
        value: em2
      - key: ipaddr
        value: 192.168.254.1
      - key: enable
        value: 1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync

opn_filter:
  - descr: Allow pfsync
    settings:
      - key: interface
        value: pfsync
      - key: log
        value: 1
      - key: type
        value: pass
      - key: ipprotocol
        value: inet
      - key: statetype
        value: keep state
      - key: source/any
        value: 1
      - key: destination/any
        value: 1

opn_hasync:
  - xpath: /opnsense/hasync
    settings:
      - key: pfsyncenabled
        value: "on"
      - key: username
        value: root
      - key: password
        value: opnsense
      - key: pfsyncinterface
        value: pfsync
      - key: pfsyncpeerip
        value: 192.168.254.2
      - key: synchronizetoip
        value: 192.168.254.2
      - key: synchronizeusers
        value: "on"
      - key: synchronizevirtualip
        value: "on"
      - key: synchronizealiases
        value: "on"
      - key: synchronizerules
        value: "on"

opn_vlan_interfaces_specific:
  - interface: opt1
    settings:
      - key: ipaddr
        value: 10.114.0.2
  - interface: opt2
    settings:
      - key: ipaddr
        value: 10.115.0.2
  - interface: opt3
    settings:
      - key: ipaddr
        value: 10.116.0.2
  - interface: opt4
    settings:
      - key: ipaddr
        value: 10.117.0.2

opn_virtualip:
  - vhid: 255
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 24
      - key: mode
        value: carp
      - key: interface
        value: wan
      - key: subnet
        value: 192.168.100.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 114
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt1
      - key: subnet
        value: 10.114.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 115
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt2
      - key: subnet
        value: 10.115.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 116
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt3
      - key: subnet
        value: 10.116.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense
  - vhid: 117
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 16
      - key: mode
        value: carp
      - key: interface
        value: opt4
      - key: subnet
        value: 10.117.0.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense

opn_alias:
  - name: ictsupport
    settings:
      - key: type
        value: network
      - key: address
        value: "192.168.103.0/24 172.16.51.61/32 172.16.51.61/32"
      - key: state
        value: present

opn_dhcpd:
  - if: opt1
    settings:
      - key: enable
        value: 1
      - key: range/from
        value: 10.114.1.0/16
      - key: range/to
        value: 10.114.1.254/16
      - key: gateway
        value: 10.114.0.1
      - key: failover_peerip
        value: 10.114.0.3
...
