---
ansible_host: 192.168.50.2
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall-secondary
      - key: domain
        value: naturalis.nl
  - xpath: /opnsense/nat
    settings:
      - key: outbound/mode
        value: disabled

opn_filter:
  - descr: Allow pfsync
    settings:
      - key: interface
        value: pfsync
      - key: log
        value: 1
      - key: type
        value: pass
      - key: ipprotocol
        value: inet
      - key: source/any
        value: 1
      - key: destination/any
        value: 1

opn_interfaces_specific:
  - interface: wan
    settings:
      - key: ipaddr
        value: 192.168.100.3
      - key: subnet
        value: 24
      - key: gateway
        value: wan_gateway
#  - if: lan
#    settings:
#      - key: ipaddr
#        value: dhcp
  - interface: pfsync
    settings:
      - key: ipaddr
        value: 192.168.254.2
  - interface: opt1
    settings:
      - key: ipaddr
        value: 10.114.0.3
  - interface: opt2
    settings:
      - key: ipaddr
        value: 10.115.0.3
  - interface: opt3
    settings:
      - key: ipaddr
        value: 10.116.0.3
  - interface: opt4
    settings:
      - key: ipaddr
        value: 10.117.0.3
...
