---
ansible_host: 192.168.1.1
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall-dw2-primary-virtualbox
      - key: domain
        value: naturalis.nl

opn_vlan_parent_interface: em1

opn_interfaces:
  - interface: wan
    settings:
      - key: if
        value: em0
      - key: ipaddr
        value: 192.168.50.12
      - key: subnet
        value: 24
      - key: descr
        value: wan
  - interface: lan
    settings:
      - key: if
        value: em1
      - key: ipaddr
        value: 192.168.1.1
      - key: subnet
        value: 24
      - key: descr
        value: lan
  - interface: pfsync
    settings:
      - key: if
        value: em2
      - key: ipaddr
        value: 192.168.254.1
      - key: enable
        value: 1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync
        
opn_virtualip:
  - vhid: 255
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 24
      - key: mode
        value: carp
      - key: interface
        value: wan
      - key: subnet
        value: 192.168.50.11
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense     

opn_filter:
  - descr: Allow pfsync
    settings:
      - key: interface
        value: pfsync
      - key: log
        value: 1
      - key: type
        value: pass
      - key: ipprotocol
        value: inet
      - key: statetype
        value: keep state
      - key: source/any
        value: 1
      - key: destination/any
        value: 1

opn_syslog:
  - xpath: /opnsense/syslog
    settings:
      - key: reverse
        value: 1
      - key: nentries
        value: 50
      - key: remoteserver
        value: 192.168.1.10
      - key: sourceip
        value: lan
      - key: ipproto
        value: ipv4
      - key: logall
        value: 1
      - key: enable
        value: 1
...
