---
ansible_host: 192.168.1.1
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall-dw2-primary-virtualbox
      - key: domain
        value: naturalis.nl

opn_vlan_parent_interface: em1

opn_interfaces:
  - interface: wan
    settings:
      - key: if
        value: em0
      - key: ipaddr
        value: dhcp
      - key: descr
        value: wan
  - interface: lan
    settings:
      - key: if
        value: em1
      - key: ipaddr
        value: 192.168.1.1
      - key: subnet
        value: 24
      - key: descr
        value: lan
  - interface: pfsync
    settings:
      - key: if
        value: em2
      - key: ipaddr
        value: 192.168.254.1
      - key: enable
        value: 1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync
        
opn_virtualip:
  - vhid: 255
    settings:
      - key: type
        value: single
      - key: subnet_bits
        value: 24
      - key: mode
        value: carp
      - key: interface
        value: wan
      - key: subnet
        value: 192.168.100.1
      - key: advskew
        value: 0
      - key: advbase
        value: 1
      - key: password
        value: opnsense     
...
