---
ansible_host: 192.168.1.1
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall-primary-virtual
      - key: domain
        value: naturalis.nl

opn_physical_interfaces:
  - interface: wan
    settings:
      - key: if
        value: em0
      - key: ipaddr
        value: dhcp
      - key: descr
        value: wan
  - interface: lan
    settings:
      - key: if
        value: em1
      - key: ipaddr
        value: 192.168.1.1
      - key: subnet
        value: 24
      - key: descr
        value: lan
  - interface: pfsync
    settings:
      - key: if
        value: em2
      - key: ipaddr
        value: 192.168.254.1
      - key: enable
        value: 1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync
...
