---
ansible_host: 192.168.1.2
ansible_user: root
ansible_ssh_pass: opnsense

opn_general:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: firewall-secondary
      - key: domain
        value: naturalis.nl
  - xpath: /opnsense/nat
    settings:
      - key: outbound/mode
        value: disabled

opn_vlan_parent_interface: em1

opn_physical_interfaces:
  - interface: wan
    settings:
      - key: if
        value: em0
      - key: ipaddr
        value: 192.168.100.3
      - key: subnet
        value: 24
      - key: gateway
        value: wan_gateway
      - key: descr
        value: wan
  - interface: lan
    settings:
      - key: if
        value: em1
      - key: ipaddr
        value: 192.168.1.2
      - key: subnet
        value: 24
      - key: descr
        value: lan
  - interface: pfsync
    settings:
      - key: if
        value: em2
      - key: ipaddr
        value: 192.168.254.2
      - key: enable
        value: 1
      - key: subnet
        value: 29
      - key: descr
        value: pfsync
...
