ansible_host: 10.124.100.11

postgresql_conf:
  - listen_addresses: "'*'"
  - max_connections: 200
  - shared_buffers: 96512MB
  - effective_cache_size: 289536MB
  - maintenance_work_mem: 2GB
  - checkpoint_completion_target: 0.7
  - wal_buffers: 16MB
  - default_statistics_target: 100
  - random_page_cost: 4
  - effective_io_concurrency: 2
  - work_mem: 24707kB
  - min_wal_size: 1GB
  - max_wal_size: 2GB
  - max_worker_processes: 40
  - max_parallel_workers_per_gather: 20
  - max_parallel_workers: 40

postgresql_users:
  - user: ndb_readonly
    password: password
    db: ndb
    priv: "CONNECT/ndb:ALL"

postgresql_databases:
  ndb2:
    owner: postgres

postgresql_privileges:
  ndb2:
    schema: explore
    roles: ndb_user_test 
    privs: SELECT
    type: table
