ansible_host: 10.124.100.11

postgresql_settings:
  - name: listen_addresses
    value: "'*'"
  - name: max_connections
    value: 200
  - name: shared_buffers
    value: 96512MB
  - name: effective_cache_size
    value: 289536MB
  - name: maintenance_work_mem
    value: 2GB
  - name: checkpoint_completion_target
    value: 0.7
  - name: wal_buffers
    value: 16MB
  - name: default_statistics_target
    value: 100
  - name: random_page_cost
    value: 1.1
  - name: effective_io_concurrency
    value: 200
  - name: work_mem
    value: 24707kB
  - name: min_wal_size
    value: 1GB
  - name: max_wal_size
    value: 2GB 
  - name: max_worker_processes
    value: 40
  - name: max_parallel_workers_per_gather
    value: 20
  - name: max_parallel_workers
    value: 40

postgresql_databases:
  - name: ndb
    owner: ndb_admin

postgresql_users:
  - name: ndb_readonly
    password: password
    db: ndb
    role_attr_flags: LOGIN
  - name: replicator
    password: password
    db: ndb
    role_attr_flags: REPLICATION

postgresql_privileges:
  - db: ndb
    state: present
    schema: explore
    privs: SELECT
    type: table
    roles: ndb_readonly
    objs: ALL_IN_SCHEMA
...
