---
ansible_host: 192.168.0.11
ansible_user: cumulus
ansible_ssh_pass: CumulusLinux!

cl_hostname: leaf01

cl_license: user@company.com|thequickbrownfoxjumpsoverthelazydog312

cl_interface:
  swp1:
    ip:
      address: 192.168.1.1/24
    link:
      speed: 100
  swp48:
    bridge:
      trunk:
        vlans:
          - 1-5
          - 10,12

cl_bond:
  uplink:
    bond:
      slaves:
        - swp1
        - swp2

cl_vlan:
  100:
    ip:
      adress:
        - 10.10.10.0/24
