---
ansible_host: 192.168.50.1
ansible_user: root
ansible_ssh_pass: opnsense

opn_singles:
  - xpath: /opnsense/system
    settings:
      - key: hostname
        value: opnsense01
      - key: domain
        value: naturalis.nl
