---
ansible_host: 192.168.56.6

postgresql_settings:
  - name: work_mem
    value: 32MB

postgresql_databases:
  - name: ndb
    owner: postgres

postgresql_schemas:
  - name: explore
    db: ndb

postgresql_users:
  - name: ndb_readonly
    password: password
    db: ndb
    role_attr_flags: LOGIN
  - name: replicator
    password: password
    db: ndb
    role_attr_flags: REPLICATION

postgresql_privileges:
  - db: ndb
    state: present
    schema: explore
    privs: SELECT
    type: table
    roles: ndb_readonly
    objs: ALL_IN_SCHEMA
...
