---
ansible_host: 192.168.56.6

postgresql_version: '12'

packages:
  - python-psycopg2
  - python3-psycopg2
  - python-ipaddress

postgresql_conf:
  - name: listen_addresses
    value: '*'
  - name: wal_level
    value: replica
  - name: max_wal_senders
    value: 4
  - name: max_replication_slots
    value: 4

postgresql_user:
  - name: ndb_readonly
    password: password
    db: ndb
    role_attr_flags: LOGIN
  - name: replicator
    password: password
    role_attr_flags: REPLICATION

postgresql_db:
  - name: ndb
    owner: postgres

postgresql_schema:
  - name: explore
    db: ndb

postgresql_privs:
  - db: ndb
    state: present
    schema: explore
    privs: SELECT
    type: table
    roles: ndb_readonly
    objs: ALL_IN_SCHEMA
    
postgresql_pg_hba:
  - dest: /etc/postgresql/12/main/pg_hba.conf
    contype: host
    users: ndb_readonly, replicator
    source: 192.168.56.0/24
    databases: ndb
    method: md5
  - dest: /etc/postgresql/12/main/pg_hba.conf
    contype: host
    users: replicator
    source: 192.168.56.0/24
    databases: replication
    method: md5

restic_repos:
- name: s3-example
  url: "s3:s3.amazonaws.com/bucket_name/restic"
  password: "dolphins"
  remote_credentials:
    aws_access_key_id: "AWS_ACCESS_KEY_ID"
    aws_secret_access_key: "AWS_SECRET_ACCESS_KEY"
  jobs:
    - command: 'restic backup /srv'
      at: '0 1  * * *'
  retention_time: '17 5 * * *'
  retention:
    last: 2
    hourly: 4
    daily: 10
    weekly: 9
    monthly: 3
    yearly: 10
    tags:
      - special
...
