---
ansible_host: 192.168.56.6

postgresql_version: '11'

packages:
  - python-psycopg2
  - python3-psycopg2
  - python-ipaddress

postgresql_set:
  - name: listen_addresses
    value: '*'

postgresql_user:
  - name: ndb_readonly
    password: password
    db: ndb
    role_attr_flags: LOGIN
  - name: replicator
    password: password
    role_attr_flags: REPLICATION

postgresql_db:
  - name: ndb
    owner: postgres

postgresql_schema:
  - name: explore
    db: ndb

postgresql_privs:
  - db: ndb
    state: present
    schema: explore
    privs: SELECT
    type: table
    roles: ndb_readonly
    objs: ALL_IN_SCHEMA
    
postgresql_pg_hba:
  - dest: /etc/postgresql/11/main/pg_hba.conf
    contype: host
    users: ndb_readonly, replicator
    source: 192.168.56.0/24
    databases: ndb
    method: md5
  - dest: /etc/postgresql/11/main/pg_hba.conf
    contype: host
    users: replicator
    source: 192.168.56.0/24
    databases: replication
    method: md5
...
