---
ansible_host: 192.168.56.7

postgresql_version: '11'

replication_user: replicator

replication_password: password

postgresql_data_directory: /var/lib/postgresql/11/main

packages:
  - python-psycopg2
  - python3-psycopg2

postgresql_set:
  - name: listen_addresses
    value: '*'
    
postgresql_user:
  - name: replicator
    password: password
    db: ndb
    role_attr_flags: REPLICATION    
...
