---
- name: Install PostgreSQL
  hosts: postgresql
  become: true
  gather_facts: true
  roles:
    - postgresql

- name: Install packages
  hosts: postgresql
  become: true
  tasks:
    - name: Install packages
      apt:
        name: python3-psycopg2 #python-psycopg2
        update_cache: yes
        state: present

- name: Create databases and users
  hosts: postgresql
  become: true
  become_user: postgres
  tasks:
    - name: Create users
      postgresql_user:
        encrypted: true
        name: "{{ item.user }}"
        password: "{{ item.password }}"
        role_attr_flags: "{{ item.roles | default(omit) }}"
        state: present
      with_items:
        - "{{ postgresql_users }}"
      when: postgresql_users is defined
      tags: postgresql_users

    - name: Create schemas
      become: true
      become_user: postgres
      postgresql_schema:
        db: "{{ item.key }}"
        name: "{{ item.value.name }}"
      with_dict: "{{ postgresql_schemas }}"
      when: postgresql_schemas is defined
      tags: postgresql_schemas

    - name: Create databases
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ item.key }}"
        owner: "{{ item.value.owner }}"
        encoding: "{{ item.value.encoding | default('UTF-8') }}"
        template: "{{ item.value.template | default('template0') }}"
      with_dict: "{{ postgresql_databases }}"
      when: postgresql_databases is defined
      tags: postgresql_databases

    - name: Set privileges
      become: true
      become_user: postgres
      postgresql_privs:
        database: "{{ item.key }}"
        schema: "{{ item.value.schema }}"
        privs: "{{ item.value.privs }}"
        type: "{{ item.value.type | default('table') }}"
        roles: "{{ item.value.roles }}"
        objs: "{{ item.value.objs }}"
      with_dict: "{{ postgresql_privileges }}"
      when: postgresql_privileges is defined
      tags: postgresql_privileges    
...
