---
- name: Install and manage PostgreSQL
  hosts: postgresql
  become: true
  gather_facts: true
  tasks:
    - include_role:
        name: postgresql
  tags:
    - postgresql

- name: Create backup
  hosts: postgresql
  become: true
  gather_facts: true
  tasks:
    - include_role:
        name: postgresql
        tasks_from: create_backup.yml
  tags:
    - create_backup

- name: Create slave
  hosts: postgresql_slave
  become: true
  gather_facts: true
  tasks:
    - include_role:
        name: postgresql
        tasks_from: create_slave.yml
  tags:
    - create_slave
...
