---
- name: Install PostgreSQL
  hosts: postgresql
  become: true
  gather_facts: true
  roles:
    - postgresql

- name: Install packages
  hosts: postgresql
  become: true
  tasks:
    - name: Install packages
      apt:
        name: python3-psycopg2 #python-psycopg2
        update_cache: yes
        state: present

- name: Configure PostgreSQL
  hosts: postgresql
  become: true
  become_user: postgres
  tasks:
    - name: Set config settings
      postgresql_set:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        register: "{{ item.register | default(omit) }}"
      with_items:
        - "{{ postgresql_settings }}"
      when: postgresql_settings is defined
      tags: postgresql_settings

    - name: Create databases
      become: true
      become_user: postgres
      postgresql_db:
        name: "{{ item.name }}"
        encoding: "{{ item.encoding | default('UTF-8') }}"
        template: "{{ item.template | default('template0') }}"
        owner: "{{ item.owner | default(postgresql_user) }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ postgresql_databases }}"
      when: postgresql_databases is defined
      tags: postgresql_databases

    - name: Create schemas
      become: true
      become_user: postgres
      postgresql_schema:
        name: "{{ item.name }}"
        db: "{{ item.db }}"
      with_items: "{{ postgresql_schemas }}"
      when: postgresql_schemas is defined
      tags: postgresql_schemas

    - name: Create users
      postgresql_user:
        encrypted: true
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        role_attr_flags: "{{ item.roles | default(omit) }}"
        state: "{{ item.state | default('present') }}"
      with_items:
        - "{{ postgresql_users }}"
      when: postgresql_users is defined
      tags: postgresql_users

    - name: Set privileges
      become: true
      become_user: postgres
      postgresql_privs:
        database: "{{ item.key }}"
        schema: "{{ item.value.schema }}"
        privs: "{{ item.value.privs }}"
        type: "{{ item.value.type | default('table') }}"
        roles: "{{ item.value.roles }}"
        objs: "{{ item.value.objs }}"
      with_dict: "{{ postgresql_privileges }}"
      when: postgresql_privileges is defined
      tags: postgresql_privileges
...
