---
- name: Install and manage PostgreSQL
  hosts: postgresql
  become: true
  gather_facts: true
  roles:
    - postgresql
  tags:
    - postgresql

- name: Create slave
  hosts: postgresql_slave
  become: true
  roles:
    - postgresql
  tags:
    - never
    - create_slave
...
