---
- name: Install and manage PostgreSQL
  hosts: postgres
  become: true
  gather_facts: true
  roles:
    - postgres
  tags:
    - postgres

- name: Create slave
  hosts: postgres_slave
  become: true
  roles:
    - postgres
  tags:
    - create_slave
  fail:
    msg: "you must use -l or --limit"
  when: ansible_limit is not defined
  run_once: true
...
