---
- name: Ansible XML
  hosts: localhost
  gather_facts: false

  tasks:
    - name: XML tricks
      xml:
        path: /tmp/core-default.xml
        xpath: /configuration
        add_children: 
          - property:
              _:
                - name: "fs.defaultFS"
                - value: "hdfs://master_ipv4_addr:9000"
          - property:
              _:
                - name: "hadoop.tmp.dir"
                - value: "/tmp/hadoop-tmp"
...


# https://raw.githubusercontent.com/qmgeng/TestJAVA/c24d387bf45ba4de4292d63733d0906060bfc525/src/conf/core-default.xml
