---
- name: Install PostgreSQL
  hosts: postgresql
  tasks:
    - name: Adding APT repository key
      when: ansible_os_family == 'Debian'
      apt_key:
        id: ACCC4CF8
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

    - name: Add PostgreSQL official APT repository
      when: ansible_os_family == 'Debian'
      apt_repository:
        repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"

    - name: Install PostgreSQL
      when: ansible_os_family == 'Debian'
      apt:
        name: "postgresql-{{postgresql_version}}"
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies for the Ansible postgres modules
      when: ansible_os_family == 'Debian'
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python-psycopg2
...
